export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

import { UserProvider } from './UserContext'; // Adjust the path to UserContext if necessary

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
